# Generated by Django 4.2.16 on 2024-10-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
