# Generated by Django 4.2.16 on 2024-10-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
